### ISSUE TITLE
As a potential <customer>, I would like to <have more information about the store> before investing in a membership.

### ISSUE THREAD

**Issue by AnthonyMejia0** [jellyhops/Super-Warehouse#7]
Story: 
As a potential <customer>, I would like to <have more information about the store> before investing in a membership.
Description:
Provide information regarding the store for prospective members.
Story Points: 1
Tasks:
-Create an function to provide information
Tests:
-Information is printed when requested
Priority: Low
Done: 
When information on the store is provide.

Anthony

**Comment by hengalvin** [comment]
void storeInfo()
{
    string line;
    ifstream fin;
    fin.open("storeinfo.txt");

    while(getline(fin,line))
    {
        cout<<line<<endl;
    }

    fin.close();
}
